Feat/marketplace logic
NotBoringCompany/webapp-api pull request #30
Opened 2022-07-10 20:44 UTC by suwandre

@shonsirsha Here are some important updates regarding the changes I want to implement. If everything is okay from your side, let's merge it.

**NOTE**: ALL of the below mentioned changes do **NOT** have security middleware implemented (we can implement this later on, just FYI).

1. `getItemsOnSale` and `getItemOnSale` is created on `marketplaceLogic.js`. I'm still unsure how slow or fast this will be, so we do need testing. But the implementation is completed :)

2. `deleteItemOnSale` is also implemented. Not sure if you also prefer to have `cancelItemOnSale` which will then call `deleteItemOnSale`, but this can be talked upon.

3. `ItemsOnSale` class on Moralis now has `duration` which is calculated by `endTime` (given by the user from the FE) minus the current time.

4. **NOT RELATED TO MARKETPLACE** `getGenesisNBMon` has now been updated to take data from Moralis. I commented the blockchain part just in case we would still need it (either for benchmark or feasibility purposes). Minting and hatching now includes adding/updating into the `Genesis_NBMons` class which I created on Moralis to store, which the `getGenesisNBMon` endpoint obtains its data from.

2022-07-11 21:01 UTC, shonsirsha commented on routes/marketplace.js
> +router.get("getItems", async (_, res) => {
Missing `/` infront of the route name

2022-07-11 21:01 UTC, shonsirsha commented on routes/marketplace.js
> +router.get("getItem", async (req, res) => {
Missing / infront of the route name

2022-07-11 21:01 UTC, shonsirsha commented on routes/marketplace.js
> +router.post("generateTxSalt", async (_, res) => {
Missing / infront of the route name

2022-07-11 21:01 UTC, shonsirsha commented on routes/marketplace.js
> +router.post("deleteItem", async (req, res) => {
Missing / infront of the route name

2022-07-11 21:07 UTC, shonsirsha commented on routes/genesisNBMonHatching.js
> +	const {id, stringMetadata, numericMetadata, boolMetadata} = req.body;
Imo it's better to have the FE to only send `id` and not the metadata. So the way this endpoint would work is to then it should look up that `id` from blockchain and fetch all the needed metadata from there.

To get nbmon data from blockchain I believe you still have the code commented out in this PR - so just uncomment that, extract it into its own function, and call it here. :)

2022-07-11 21:19 UTC, shonsirsha commented on logic/genesisNBMonLogic.js
> +const { query } = require("express");
I believe this isn't used. You probably imported it by accident - so you could remove it

2022-07-11 21:21 UTC, shonsirsha requested changes
Please address the changes before merging :) Also please pull from dev before you start making changes.

2022-07-15 10:56 UTC, suwandre commented
Everything else has been updated apart from the /updateHatchedNBMon change. Once we update the RPC URL to Matic, I'll keep this in mind and change it asap. Thanks!

2022-07-15 10:56 UTC, merged